# Create and run a local RAG pipeline from scratch

## Importing PDF from scratch

In [2]:
import os
import requests

# Get pdf path
pdf_path = "human_nutrition_text"

# Download pdf
if not os.path.exists(pdf_path):
    print(f"[INFO] File doesnt exist, downloading...")

    # Enter the URL of the PDF
    url = "https://pressbooks.oer.hawaii.edu/humannutrition2/open/download?type=pdf"
    
    # The local filename to save the downloaded file
    filename = pdf_path

    # Send a GET request to the URL
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        # Open the file and save it
        with open(filename, "wb") as file:
            file.write(response.content)
        print(f"[INFO] The file has been downloaded and saved as {filename}")
    else:
        print(f"[INFO] Failed to download the file. Status code: {response.status_code}")
else:
    print(f"File {pdf_path} exists")

File human_nutrition_text exists

In [3]:
import fitz
from tqdm.auto import tqdm

def text_formatter(text:str) -> str:
    """ Performs minor formatting on text. """
    cleaned_text = text.replace("\n", " ").strip()
    return cleaned_text

def open_and_read_pdf(pdf_path : str) -> list[dict]:
    doc = fitz.open(pdf_path)
    pages_and_texts = []
    for page_number, page in tqdm(enumerate(doc)):
        text = page.get_text()
        text = text_formatter(text)
        pages_and_texts.append({"page_number":page_number - 41, 
                                "page_char_count": len(text),
                                "page_word_count": len(text.split(" ")),
                                "page_sentence_count_raw": len(text.split(". ")),
                                "page_token_count": len(text) / 4, 
                                "text": text})
    return pages_and_texts

pages_and_texts = open_and_read_pdf(pdf_path = pdf_path)
pages_and_texts[:2]

0it [00:00, ?it/s]

[{'page_number': -41,
  'page_char_count': 29,
  'page_word_count': 4,
  'page_sentence_count_raw': 1,
  'page_token_count': 7.25,
  'text': 'Human Nutrition: 2020 Edition'},
 {'page_number': -40,
  'page_char_count': 0,
  'page_word_count': 1,
  'page_sentence_count_raw': 1,
  'page_token_count': 0.0,
  'text': ''}]

In [4]:
import random

random.sample(pages_and_texts, k=5)

[{'page_number': 422,
  'page_char_count': 1710,
  'page_word_count': 282,
  'page_sentence_count_raw': 16,
  'page_token_count': 427.5,
  'text': 'turnover rate. During exercise, especially when it is performed for  longer than two to three hours, muscle tissue is broken down and  some of the amino acids are catabolized to fuel muscle contraction.  To avert excessive borrowing of amino acids from muscle tissue to  synthesize energy during prolonged exercise, protein needs to be  obtained from the diet. Intense exercise, such as strength training,  stresses muscle tissue so that afterward, the body adapts by  building bigger, stronger, and healthier muscle tissue. The body  requires protein post-exercise to accomplish this. The IOM does  not set different RDAs for protein intakes for athletes, but the AND,  the American College of Sports Medicine, and Dietitians of Canada  have the following position statements4:  Nitrogen balance studies suggest that dietary protein intake  necessary to support nitrogen balance in endurance athletes  ranges from 1.2 to 1.4 grams per kilogram of body weight per  day.  Recommended protein intakes for strength-trained athletes  range from approximately 1.2 to 1.7 grams per kilogram of  weight per day.  An endurance athlete who weighs 170 pounds should take in 93  to 108 grams of protein per day (170 ÷ 2.2 × 1.2 and 170 ÷ 2.2 ×  1.4). On a 3,000-kilocalorie diet, that amount is between 12 and 14  4. American College of Sports Medicine, Academy of  Nutrition and Dietetics, and Dietitians of Canada. (2009).  Joint Position Statement: Nutrition and Athletic  Performance. Medicine & Science in Sports & Exercise,  41(3), 709-31. http://journals.lww.com/acsm-msse/ fulltext/2009/03000/ Nutrition_and_Athletic_Performance.27.aspx. Accessed  September 28, 2017.  422  |  Proteins, Diet, and Personal Choices'},
 {'page_number': 799,
  'page_char_count': 1524,
  'page_word_count': 259,
  'page_sentence_count_raw': 20,
  'page_token_count': 381.0,
  'text': 'over-the-counter painkillers. Some studies suggest that very high  amounts of caffeine have been linked to babies born with low birth  weights. The American Journal of Obstetrics and Gynecology  released a report, which found that women who consume 200  milligrams or more of caffeine a day (which is the amount in 10  ounces of coffee or 25 ounces of tea) increase the risk of  miscarriage7.  Consuming large quantities of caffeine affects the pregnant  mother as well, leading to irritability, anxiety, and insomnia. Most  experts agree that small amounts of caffeine each day are safe  (about one 8-ounce cup of coffee a day or less)8. However, that  amount should not be exceeded.  Foodborne Illness  For both mother and child, foodborne illness can cause major health  problems. For example, the foodborne illness caused by the bacteria  Listeria monocytogenes can cause spontaneous abortion and fetal  or newborn meningitis. According to the CDC, pregnant women  are twenty times more likely to become infected with this disease,  which is known as listeriosis, than nonpregnant, healthy adults.  Symptoms include headaches, muscle aches, nausea, vomiting, and  7. Weng X, Odouli R, Li DK. (2008). Maternal caffeine  consumption during pregnancy and the risk of  miscarriage: a prospective cohort study. American  Journal of Obstetrics & Gynecology, 198, 279.e1-279.e8.  8. American Medical Association. (2008). Complete Guide to  Prevention and Wellness. Hoboken, NJ: John Wiley &  Sons, Inc., 495.  Pregnancy  |  799'},
 {'page_number': 28,
  'page_char_count': 966,
  'page_word_count': 163,
  'page_sentence_count_raw': 11,
  'page_token_count': 241.5,
  'text': '3. Ovo-vegetarian. This type of vegetarian diet includes eggs but  not dairy products.  4. Vegan. This type of vegetarian diet does not include dairy,  eggs, or any type of animal product or animal by-product.  Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.  These activities are  available in the web-based textbook and not available in the  downloadable versions (EPUB, Digital PDF, Print_PDF, or  Open Document).  Learning activities may be used across various mobile  devices, however, for the best user experience it is strongly  recommended that users complete these activities using a  desktop or laptop computer and in Google Chrome.    An interactive or media element has been  excluded from this version of the text. You can  view it online here:  http://pressbooks.oer.hawaii.edu/ humannutrition2/?p=55    28  |  Lifestyles and Nutrition'},
 {'page_number': 762,
  'page_char_count': 594,
  'page_word_count': 116,
  'page_sentence_count_raw': 6,
  'page_token_count': 148.5,
  'text': 'Secretariat  of the Pacific  Community  / CC  BY-NC-ND  4.0  The overall key messages to the SPC Dietary Guidelines are to  consume a variety of foods each day from the 3 food groups.  However, food should be consumed in moderation as too much  of any one food can be unhealthy. Foods should be consumed in  recommended amounts. In addition, every effort should be made to  consuming foods that are locally sourced. See the image below for a  depiction of the key messages of the SPC Dietary Guidelines.  Figure 12.9 The Pacific Guide to Healthy Eating  762  |  Pacific Based Dietary Guidelines'},
 {'page_number': 689,
  'page_char_count': 1080,
  'page_word_count': 191,
  'page_sentence_count_raw': 15,
  'page_token_count': 270.0,
  'text': 'Manganese  UNIVERSITY OF HAWAI‘I AT MĀNOA FOOD SCIENCE AND HUMAN  NUTRITION PROGRAM AND HUMAN NUTRITION PROGRAM  Manganese is a cofactor for enzymes that are required for  carbohydrate and cholesterol metabolism, bone formation, and the  synthesis of urea. Those who suffer from liver failure are at greater  risk for manganese toxicity because the mineral’s homeostasis is  maintained largely by the liver with excretion of excess manganese  occurring via bile. Manganese deficiency is uncommon. If a  deficiency occurs from elimination from the diet, signs and  symptoms include but are not limited to nausea, vomiting,  dermatitis, decreased growth of hair and nails, and poor bone  formation and skeletal defects.1    Dietary Reference Intake of Manganese  The recommended intake for manganese is 2.3 mg per day for  adult males and 1.8 mg per day for adult females. The Tolerable  Upper Intake Level for adults is 11 mg/day.  1. Gropper, S. A. S., Smith, J. L., & Carr, T. P. (2018).  Advanced nutrition and human metabolism. Boston, MA:  Cengage Learning.  Manganese  |  689'}]

In [6]:
import pandas as pd
df = pd.DataFrame(pages_and_texts)
df.head()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text
0,-41,29,4,1,7.25,Human Nutrition: 2020 Edition
1,-40,0,1,1,0.00,
2,-39,320,54,1,80.00,Human Nutrition: 2020 Edition UNIVERSITY OF ...
3,-38,212,32,1,53.00,Human Nutrition: 2020 Edition by University of...
4,-37,797,147,3,199.25,Contents Preface University of Hawai‘i at Mā...

In [7]:
df.describe()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count
count,1208.00000,1208.000000,1208.000000,1208.000000,1208.000000
mean,562.50000,1148.004139,199.499172,10.519868,287.001035
std,348.86387,560.382275,95.830681,6.548495,140.095569
min,-41.00000,0.000000,1.000000,1.000000,0.000000
25%,260.75000,762.000000,134.000000,5.000000,190.500000
50%,562.50000,1231.500000,216.000000,10.000000,307.875000
75%,864.25000,1603.500000,272.000000,15.000000,400.875000
max,1166.00000,2308.000000,430.000000,39.000000,577.000000

### Further text processing (splitting pages into sentences)

Two ways to do this : 
1. Do this by splitting on `". "`.
2. We can do this with a NLP library like Spacy or NLTK

In [23]:
from spacy.lang.en import English

nlp = English()

# Add a sentencizer pipeline
nlp.add_pipe("sentencizer")

# Create document instance as an example
doc = nlp("This is a sentence. This is another sentence. I like potatoes.")
assert len(list(doc.sents)) == 3

# Print out sentences split
list(doc.sents)

[This is a sentence., This is another sentence., I like potatoes.]

In [26]:
for item in tqdm(pages_and_texts):
    item["sentences"] = list(nlp(item["text"]).sents)

    # make sure all sentences are strings. The default type is spacy datatype
    item["sentence"] = [str(sentence) for sentence in item["sentences"]]

    # count the sentences
    item["page_sentence_count_spacy"] = len(item["sentences"])

  0%|          | 0/1208 [00:00<?, ?it/s]

In [27]:
random.sample(pages_and_texts, k=1)

[{'page_number': 1045,
  'page_char_count': 308,
  'page_word_count': 53,
  'page_sentence_count_raw': 3,
  'page_token_count': 77.0,
  'text': 'effectively. By contrast, eating a variety of foods from all food groups  fuels the body by providing what it needs to produce energy,  promote metabolic activity, prevent micronutrient deficiencies,  ward off chronic disease, and  bolstering a sense of overall health  and well-being.  Introduction  |  1045',
  'sentences': [effectively.,
   By contrast, eating a variety of foods from all food groups  fuels the body by providing what it needs to produce energy,  promote metabolic activity, prevent micronutrient deficiencies,  ward off chronic disease, and  bolstering a sense of overall health  and well-being.,
    Introduction  |  1045],
  'sentence': ['effectively.',
   'By contrast, eating a variety of foods from all food groups  fuels the body by providing what it needs to produce energy,  promote metabolic activity, prevent micronutrient deficiencies,  ward off chronic disease, and  bolstering a sense of overall health  and well-being.',
   ' Introduction  |  1045'],
  'page_sentence_count_spacy': 3}]

In [28]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,199.50,10.52,287.00,10.32
std,348.86,560.38,95.83,6.55,140.10,6.30
min,-41.00,0.00,1.00,1.00,0.00,0.00
25%,260.75,762.00,134.00,5.00,190.50,5.00
50%,562.50,1231.50,216.00,10.00,307.88,10.00
75%,864.25,1603.50,272.00,15.00,400.88,15.00
max,1166.00,2308.00,430.00,39.00,577.00,28.00

### Chunking our sentences together 

The concept of splitting larger pieces of text into smaller ones is often referred to as text splitting or chunking.
    We'll split into groups of 10 sentences.